name: apiverve_cryptogram
description: Cryptogram Generator creates letter substitution cipher puzzles where each letter is replaced with another letter consistently throughout the text.
version: 1.1.14
homepage: https://apiverve.com/marketplace/cryptogram?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/cryptogram-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
